### ISSUE TITLE
add reload command

### ISSUE THREAD

**Issue by Ownasaurus** [Ownasaurus/TASLink#14]
similar to reset but reloads the original file

**Comment by TheMas3212** [comment]
looking at this, might have a go in implementing it
is this something like what you looking for? (but in a single command)
1. save current run to a temp file
2. remove current run
3. load temp file back in as a new run

**Comment by Ownasaurus** [comment]
Well, in the case you describe, I think it would be functionally equivalent to a reset. I was thinking about only supported it for saved runs. If you wanted to reload the original file without saving your changes, that's what the reload command would be for.
